### ISSUE TITLE
Extensions: Install Extension does not exist

### ISSUE THREAD

**Issue by farina** [ziyasal/vscode-open-in-github#1]
In the latest version of Visual Studio Code, I do not see command options for "extensions." Is it possible that they no longer support this? Doesn't make sense, I'm sure I am doing something wrong.

**Comment by theproducer** [comment]
This is very interesting - based on the package.json, this is for a currently unreleased version of VS Code that has Extensions support (0.9.8 - currently 0.9.2 is released).

MS usually releases beta updates to VS Code at the beginning of every month.  I'd sign up here:
https://www.instant.ly/s/Y5nt1/nav#p/186a0  to the insiders program to get an email when its released.

**Comment by farina** [comment]
Thank you for the response. After seeing this extension, I just had assumed it was an available feature :).
