### ISSUE TITLE
Updating VSCode Marketplace

### ISSUE THREAD

**Issue by ryanmcdermott** [ziyasal/vscode-open-in-github#108]
This is a great extension! Is there any plan of updating the latest version for the VSCode marketplace? It could be useful to release the custom provider change: 70ccbd42681e6218e1e8b87faa6a66f059964637

**Comment by ryanmcdermott** [comment]
Any update on this? Thank you!

**Comment by ziyasal** [comment]
Hi @ryanmcdermot, Thank you for your comment, I'll have a look asap

**Comment by ryanmcdermott** [comment]
Thanks, I really appreciate it!

**Comment by drewlustro** [comment]
+1

**Comment by ryanmcdermott** [comment]
Any update on this? Thank you! Sorry for the bother

**Comment by kjg** [comment]
I would also love to see what's in master get deployed to the marketplace
