### ISSUE TITLE
Locate or specify github server name

### ISSUE THREAD

**Issue by RoscoP** [ziyasal/vscode-open-in-github#19]
It would be great if this extension allowed you to use another domain for the project.  I'm unsure how vscode's git integration works, but I believe the url for the remote system is in the git config; `git config --get remote.origin.url` should return it, but I think that depends on 'origin' as the name.

Either way, this would let you specify a custom github server (like [GitHub enterprise](https://enterprise.github.com/home) accounts).

**Comment by Justin-Credible** [comment]
Yeah, it would be great if we could set a workspace config for a URL prefix so we could use our internal GitHub location.

**Comment by testerez** [comment]
+1 I'd like to be able to use it with github enterprise.
