### ISSUE TITLE
No handler found for the command 'openInGitHub'

### ISSUE THREAD

**Issue by isidorn** [ziyasal/vscode-open-in-github#2]
I have latest VSCode and I have installed the open in git hub extension.
When I do the "Open in GitHub" action I get the "No handler found for the command 'openInGitHub'"

Might it be that this extension is not working with latest VS Code?

**Comment by ziyasal** [comment]
hi @isidorn  Thank you for your feedback, I'll take a look asap.

**Comment by captncraig** [comment]
I get this as well

**Comment by gep13** [comment]
Same here...

![image](https://cloud.githubusercontent.com/assets/1271146/11251958/ae8cd9d6-8e2b-11e5-8644-7f24db01dfc2.png)

**Comment by ziyasal** [comment]
hi @gep13  I have updated my vscode and I got this warning too.  I'll fix it asap.

**Comment by ziyasal** [comment]
hi all, I'll publish new version asap.

**Comment by ziyasal** [comment]
Hi all, I've pushed new version.
