### ISSUE TITLE
No support for subdirectory workspaces

### ISSUE THREAD

**Issue by bradyholt** [ziyasal/vscode-open-in-github#29]
When opening a sub-directory of a git repository in vscode, this extension is not able to resolve the git repository information and therefore fails to open files in the browser.

There needs to be support for finding the root repository from relative to the vscode workspace root.

Worked was done to support this in: https://github.com/ziyasal/vscode-open-in-github/pull/27 but was subsequently reverted after merged and I am not sure why.

**Comment by ziyasal** [comment]
Hi @bradyholt sorry for late reply, there was a problem with creating url and l haven't find a time to find why. So l have reverted it to fix problem. I will take a look at to it , asap.

**Comment by bradyholt** [comment]
No worries, thanks for the note.  I am actually working on another implementation that I think will be better so I will submit that and see what you think.  I'll test it on OSX and Windows.
