### ISSUE TITLE
Open line in github does not work in version 1.2.0

### ISSUE THREAD

**Issue by ziluvatar** [ziyasal/vscode-open-in-github#33]
It always open the branch tree instead of the file with selected line.
I am using OS X El Capitan

You can find more info in the Pull Request I prepared to fix it: https://github.com/ziyasal/vscode-open-in-github/pull/32

**Comment by gdziadkiewicz** [comment]
@ziluvatar I am sorry for your inconvenience and happy that you fixed the problem. I feel responsible as I did not test my changes on OS X. I did not suspect that the VS Code API responses are not the same on all operating systems.

Did you test your changes on Windows or Linux? If not then I can do that today and write the results under your PR.

For future development it would be a good idea to find people with each of supported operating systems to test the PR before merging. Something like a mandatory checklist? Other approach to the problem would be adding e2e tests to the project and connecting to CI. AppVeyor can run the tests on Windows and TravisCI can run OS X and Linux.

**Comment by ziluvatar** [comment]
@gdziadkiewicz I have tested it in OS X El Capitan and Windows 10. I can install a linux distro (i.e: ubuntu) in virtualbox and take a look as well.

I will take a look to this https://code.visualstudio.com/docs/extensions/testing-extensions

**Comment by ziluvatar** [comment]
>  I did not suspect that the VS Code API responses are not the same on all operating systems.
Not sure if that happens but I think it was failing on Windows as well, could you take a look? (just to be sure nothing weird is going on when I try it)

**Comment by gdziadkiewicz** [comment]
I checked every combination of line/file/repo option with github, bitbucket and visual studio team services, on Windows 10, and it worked for all of the combinations. I will recheck it later today, as I am currently away from my PC.

The article about extensions testing is good. Example tests generated by the Yo visual studio code extension generator are also a good starting point for writing tests. I've implemented such tests for htmlwrap extension.  It would be great to have them.

**Comment by gdziadkiewicz** [comment]
@ziluvatar I am not able to reproduce the error on Windows 10 with extension version 1.2.0. Opening of file works fine on github, bitbucket and visual studio team services. I am using Visual Studio Code version 1.3.1.

**Comment by ziluvatar** [comment]
It's weird :( Anyway I just double checked with a work mate and it is happening in mac for sure.

@gdziadkiewicz Can you try my PR in windows please? I don't trust my test for now until I find what happened.

**Comment by gdziadkiewicz** [comment]
@ziluvatar I also tested your PR yesterday on Windows - it works correctly :)
