### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ChrisCinelli** [ziyasal/vscode-open-in-github#5]
When I click on "Open in GitHub" nothing happend.
 I am using a Mac

**Comment by ziyasal** [comment]
Hi @ChrisCinelli, Thank you for feedback, I'll take alook asap.

**Comment by jboctor** [comment]
I'm here to verify this is as well. The only other extension I have is the phpcs one. Hope this can get resolved soon.

**Comment by bradyholt** [comment]
:+1: same here, on Mac

**Comment by bradyholt** [comment]
Pretty sure, `open` command should be used for Max OSX rather than `start`.  Here: https://github.com/ziyasal/vscode-open-in-github/blob/master/src/extension.js#L57
