### ISSUE TITLE
Add parameter to specify http or https url

### ISSUE THREAD

**Issue by jgarec** [ziyasal/vscode-open-in-github#65]
Hi,

Our gitlab CE only works on http (not https). Could you add a parameter (like secure or protocol) to specify if the url must start with http or https

https://github.com/ziyasal/vscode-open-in-github/blob/29788d5e0874eea35bd18caaa40299a99d934010/src/gitProvider.js#L72

Thx

**Comment by Fazered** [comment]
This would be great.

**Comment by chandramuralis** [comment]
I still don't see this setting after installing latest version of this extension.
