### ISSUE TITLE
branch is not selected properly

### ISSUE THREAD

**Issue by antxxxx** [ziyasal/vscode-open-in-github#7]
The branch that is chosen for the URL is not the active branch in the local repository.
I did have a quick look and you may be able to use git-rev (https://github.com/tblobaum/git-rev) to get the active branch but only once the pull request at https://github.com/tblobaum/git-rev/pull/14 has been merged in

**Comment by amaechler** [comment]
:+1:

**Comment by isidorn** [comment]
+1 the current active branch is not respected 
files on master are always opened
