### ISSUE TITLE
[Bug] ".git" removed if repository name is <user>.github.io

### ISSUE THREAD

**Issue by abinavseelan** [ziyasal/vscode-open-in-github#73]
# Bug - ".git" removed if repository name is <user>.github.io

First of all, love the extension ❤️ 😄 

## Context

I have a repository `abinavseelan.github.io`. When I use the extension to go to a specific line, the final url that I'm taken to is `https://github.com/abinavseelan/abinavseelanhub.io/blob/master/index.html#L16-L24`

The `.git` in `abinavseelan.github.io` is removed.

## Potential fix

Looks like the bug is originating from here https://github.com/ziyasal/vscode-open-in-github/blob/master/src/gitProvider.js#L13 🙂 

I can raise a PR for this in a couple of hours 🙂

**Comment by abinavseelan** [comment]
Raised a PR to fix this here : https://github.com/ziyasal/vscode-open-in-github/pull/74 🐨

**Comment by ziyasal** [comment]
Hi @abinavseelan pr merged and a new version published so I'm closing this.
