### ISSUE TITLE
Doesn't work with bitbucket URLs

### ISSUE THREAD

**Issue by DanielAsher** [ziyasal/vscode-open-in-github#82]
Hi,

was looking forward to using this!

I've set the provider to be bitbucket, and when calling Open in Github I get this url:

`https://bitbucket.org/team/project/src/branchfolder/branchname/dir1/dir2/sourcefile.swift#cl-142`

which produces an error page (see below).

It looks like it needs to produce:

`https://bitbucket.org/team/project/src/a285d517f4b9db31acacfee01018ace7577e939cdir1/dir2/sourcefile.swift#sourcefile.swift-142`

or

`https://bitbucket.org/team/project/commits/b6eac64dbc5e2859d78bb53d16c19cc561a15511`

Ideally both.

More power to you!

<img width="449" alt="bitbucket failure" src="https://user-images.githubusercontent.com/7915553/38013079-b6279150-325b-11e8-9eeb-b7beb4663cc2.png">

**Comment by jwulf** [comment]
I have a patch in my fork that fixes this. See #86

**Comment by ziyasal** [comment]
It fixed in latest release.
