### ISSUE TITLE
Copies link but does not open in Github

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [ziyasal/vscode-open-in-github#96]
Extension Ver. 1.3.5

I am able to copy the link, but when I do open in Github, nothing happens. I checked the console, there is no error message. Maybe it is not able to identify my web-browser. How can I further investigate this issue?

**Comment by ziyasal** [comment]
Hi @Agarwal-Nikhil, thank you for filling the issue, out, could you please share Vs Code (`Help-> About`) and os details?

**Comment by Agarwal-Nikhil** [comment]
Hi @ziyasal ! 

OS: Ubuntu 18.04
Web Browser: Google Chrome
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by ziyasal** [comment]
Hi @Agarwal-Nikhil, a new version has released recently, it'd be great if you can try it out and update issue.

**Comment by dnohales** [comment]
It started to happening to me while ago and uninstalled the extension. I installed it again today to give it another try and it still happening.

```
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```

**Comment by dnohales** [comment]
Looks like the problem is with the `open` package, I replaced it with my own `open` function in the extension and it works:

```
function open(url) {
    childProcess.spawn('xdg-open', [url]);
}
```
