### ISSUE TITLE
Unknown Git provider

### ISSUE THREAD

**Issue by rusty-key** [ziyasal/vscode-open-in-github#97]
Hi!

Today I started getting error alerts when trying to use this extension: `Unknown Git provider. Error: unknown Provider`.
Yesterday extension worked fine. I didn't make any changes in my environment recently, though maybe vscode updated in the background.

Here are my details:
vscode: Version 1.25.1 (1.25.1)
macOS: 10.13.5
xcode: 9.4.1

**Comment by ziyasal** [comment]
@rusty-key  Thanks for filing an issue! What is the extension version, there might be an issue with the latest one 🤔

**Comment by rusty-key** [comment]
@ziyasal, 1.7.0

**Comment by ziyasal** [comment]
Hi @rusty-key, Current version of `ziyasal/vscode-open-in-github` is 1.3.5. I think you are using `https://marketplace.visualstudio.com/items?itemName=sysoev.vscode-open-in-github` this extension, it looks like a fork this, so I suggest file an issue in their repo ➡️ https://github.com/d4rkr00t/vscode-open-in-github.
Thanks.

**Comment by kycuong-stripe** [comment]
@ziyasal Here's a screenshot of the error within VS Code for me: 

![image](https://user-images.githubusercontent.com/29717608/43108483-e7ed44d6-8e96-11e8-9b27-3b931d932f75.png)

On: 

* `ziyasal.vscode-open-in-github` v1.3.5
* VS Code v1.25.1
* macOS 10.13.3

It also looks like the [latest Travis build](https://travis-ci.org/ziyasal/vscode-open-in-github/jobs/406214997) failed.

I _love_ this extension and use it everyday. Looking forward to a fix!

**Comment by ctaggart** [comment]
I'm hitting this too. I tried setting `openInGitHub.gitHubDomain` to our Github Enterprise domain, but looks like a v1.3.5 problem. VS Code 1.25.1 as well on Windows.

**Comment by ziyasal** [comment]
@rusty-key @kycuong-stripe  @ctaggart Hi, thank you for reporting that, I could not reproduce on windows and unfortunately, I have no mac at the moment but I will try to have a look asap, meanwhile, it'd be awesome if someone can have a look.

**Comment by Niels-NTG** [comment]
I'm experiencing exactly the same issue. I've tried setting `providerType` to `"gitlab"` and `gitHubDomain` to our custom Gitlab host, something I hadn't had to set before, but this doesn't do anything.

I'm using:
• ziyasal/vscode-open-in-github v1.3.5
• vscode v1.25.1
• macOS 10.13.6

**Comment by jonaskello** [comment]
This seems like a really nice extension. Unfortunately it does not work for me either. I use gitlab and have set the same as @Niels-NTG but I get an error toast with "Unknown Git provider. Error: unknown Provider". I'm also using 1.3.5 installed through vscode and macos 10.13.6.

**Comment by jonaskello** [comment]
I also have Windows 10, so I tried the same thing there but same result. Error "Unknown Git provider. Error: unknown Provider".

**Comment by lnunno** [comment]
Really would like to use this extension, but unusable in this state with GitHub Enterprise. ☹️

**Comment by Lyncredible** [comment]
I hit the same problem. It worked after setting `openInGitHub.gitHubDomain` and then restarting VSCode.

**Comment by nooby-noob** [comment]
I love this extention too.

if you use custom domain repository like `github.example.com`, set `openInGitHub.providerType: "github"` in your user settings.

before this https://github.com/ziyasal/vscode-open-in-github/commit/5fae04014cee8a7456a37a618a903e8a043f0acc commit, the default providerType was `gitlab` but it would works with using `github` provider because gitlab and github are the same url style...

**Comment by lnunno** [comment]
For completeness sake, I had to add:

```
"openInGitHub.providerType": "github",
"openInGitHub.gitHubDomain": "github.mycompany.foo"
```

In my settings and now it works!

**Comment by tillbrodbeck-oviva** [comment]
Hi I always get the unknown provider error, for gitlab, for GitHub it works out of the box.
I tried setting this but it does not change anything:
```json
{
    "openInGitHub.gitHubDomain": "git.vshn.net",
    "openInGitHub.customProviderPath": "https://git.vshn.net/oviva",
    "openInGitHub.requireSelectionForLines": false,
    "openInGitHub.useCommitSHAInURL": false,
    "openInGitHub.providerType": "gitlab"
}
```
